def pedido_muestra() -> dict:
    """Pedido de ejemplo (basado en el PDF de ECOGRASAS) con 8% y exento."""
    return {
        'id': 3610,
        'cliente': 'J-00028027-4',
        'descripcion_cliente': 'PANDOCK, C. A.',
        'direccion_cliente': ('AV ROMULO GALLEGOS EDIF PANDOCK PISO PB LOCAL 26 '
                              'SECTOR MONTE CRISTO CARACAS MIRANDA ZONA POSTAL 1071'),
        'nombre_vendedor': 'VENTAS INTERNAS',
        'vendedor': '04',
        'precio': 'P1',
        'comentario': 'PRECIO AUTORIZADO POR JUAN M. VILLEGAS\nCREDITO 10 DIAS',
        'productos': {
            'PT0304001': {'descripcion': 'MANTECA VEGETAL LA COJEDEÑA PANADERA CAJA 10 kg',
                          'cantidad': 20.0, 'descuento': 0, 'impuesto': 8,
                          'precio_sin_iva': 38.00, 'precio_con_descuento': 38.00,
                          'subtotal': 760.00, 'total_sin_dcto': 760.00,
                          'monto_iva': 3.04, 'precio_venta': 41.04, 'precio': 41.04, 'peso_item': 0},
            'PT0402001': {'descripcion': 'MARGARINA LA COJEDEÑA MULTIUSO BAJA EN SAL 05 kg (E)',
                          'cantidad': 92.0, 'descuento': 0, 'impuesto': 0,
                          'precio_sin_iva': 15.50, 'precio_con_descuento': 15.50,
                          'subtotal': 1426.00, 'total_sin_dcto': 1426.00,
                          'monto_iva': 0.0, 'precio_venta': 15.50, 'precio': 15.50, 'peso_item': 0},
            'PT0402003': {'descripcion': 'MARGARINA LA COJEDEÑA MULTIUSO CON SAL 05 kg (E)',
                          'cantidad': 36.0, 'descuento': 0, 'impuesto': 0,
                          'precio_sin_iva': 15.50, 'precio_con_descuento': 15.50,
                          'subtotal': 558.00, 'total_sin_dcto': 558.00,
                          'monto_iva': 0.0, 'precio_venta': 15.50, 'precio': 15.50, 'peso_item': 0},
            'PT0305003': {'descripcion': 'MANTECA VEGETAL LA COJEDEÑA COMPUESTA CAJA 10 Kg',
                          'cantidad': 38.0, 'descuento': 0, 'impuesto': 8,
                          'precio_sin_iva': 28.00, 'precio_con_descuento': 28.00,
                          'subtotal': 1064.00, 'total_sin_dcto': 1064.00,
                          'monto_iva': 2.24, 'precio_venta': 30.24, 'precio': 30.24, 'peso_item': 0},
        },
        'base_16': 0.0, 'iva_16': 0.0,
        'base_8': 1824.00, 'iva_8': 145.92,
        'exento': 1984.00,
        'baseimponible': 1824.00, 'iva_total': 145.92,
        'total_bruto': 3808.00, 'total_neto': 3953.92,
        'peso_total': 0.0,
    }
